import { boolean, timestamp, text, unique, pgTable, jsonb, integer, bigint, numeric } from 'drizzle-orm/pg-core'

export const user = pgTable('user', {
  id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(),
  emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'),
  createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(),
  language: text('language').notNull().default('ar'), timezone: text('timezone').notNull().default('Africa/Cairo'), totalumApiKeyCiphertext: text('totalumApiKeyCiphertext'), totalumApiKeyUpdatedAt: timestamp('totalumApiKeyUpdatedAt'),
})
export const session = pgTable('session', {
  id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(),
  createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull(),
})
export const account = pgTable('account', {
  id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(),
})
export const verification = pgTable('verification', {
  id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').defaultNow(), updatedAt: timestamp('updatedAt').defaultNow(),
})
export const projectAccess = pgTable('project_access', {
  id: text('id').primaryKey(), userId: text('userId').notNull(), projectId: text('projectId').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow(),
}, (table) => ({ userProjectUnique: unique().on(table.userId, table.projectId), projectUnique: unique().on(table.projectId) }))

export const providers = pgTable('providers', { id: text('id').primaryKey(), userId: text('user_id').notNull(), slug: text('slug').notNull(), name: text('name').notNull(), status: text('status').notNull().default('disabled'), capabilities: jsonb('capabilities').notNull().default({}), adapterKey: text('adapter_key'), endpoint: text('endpoint'), metadata: jsonb('metadata').notNull().default({}), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(), deletedAt: timestamp('deleted_at', { withTimezone: true }) }, (table) => ({ providerUnique: unique().on(table.userId, table.slug) }))
export const providerCredentials = pgTable('provider_credentials', { id: text('id').primaryKey(), userId: text('user_id').notNull(), providerId: text('provider_id').notNull(), label: text('label').notNull(), ciphertext: text('ciphertext').notNull(), keyVersion: text('key_version').notNull(), status: text('status').notNull().default('active'), expiresAt: timestamp('expires_at', { withTimezone: true }), lastRotatedAt: timestamp('last_rotated_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(), revokedAt: timestamp('revoked_at', { withTimezone: true }) }, (table) => ({ credentialUnique: unique().on(table.userId, table.providerId, table.label) }))
export const models = pgTable('models', { id: text('id').primaryKey(), userId: text('user_id').notNull(), providerId: text('provider_id').notNull(), modelKey: text('model_key').notNull(), displayName: text('display_name').notNull(), capabilities: jsonb('capabilities').notNull().default({}), limits: jsonb('limits').notNull().default({}), pricing: jsonb('pricing').notNull().default({}), status: text('status').notNull().default('disabled'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(), deletedAt: timestamp('deleted_at', { withTimezone: true }) }, (table) => ({ modelUnique: unique().on(table.userId, table.providerId, table.modelKey) }))
export const providerConnections = pgTable('provider_connections', { id: text('id').primaryKey(), userId: text('user_id').notNull(), providerId: text('provider_id').notNull(), credentialId: text('credential_id'), label: text('label').notNull(), endpoint: text('endpoint').notNull(), status: text('status').notNull().default('disabled'), priority: integer('priority').notNull().default(100), weight: integer('weight').notNull().default(1), healthState: text('health_state').notNull().default('unknown'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() }, (table) => ({ connectionUnique: unique().on(table.userId, table.providerId, table.label) }))
export const routingPolicies = pgTable('routing_policies', { id: text('id').primaryKey(), userId: text('user_id').notNull(), name: text('name').notNull(), scope: text('scope').notNull().default('user'), strategy: text('strategy').notNull().default('priority'), config: jsonb('config').notNull().default({}), enabled: boolean('enabled').notNull().default(false), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() }, (table) => ({ routingUnique: unique().on(table.userId, table.name) }))
export const providerHealth = pgTable('provider_health', { id: text('id').primaryKey(), userId: text('user_id').notNull(), providerId: text('provider_id').notNull(), connectionId: text('connection_id'), state: text('state').notNull().default('unknown'), latencyMs: integer('latency_ms'), errorRate: numeric('error_rate', { precision: 6, scale: 5 }), checkedAt: timestamp('checked_at', { withTimezone: true }).notNull().defaultNow(), details: jsonb('details').notNull().default({}) }, (table) => ({ healthUnique: unique().on(table.userId, table.providerId, table.connectionId) }))
export const aiRequests = pgTable('ai_requests', { id: text('id').primaryKey(), userId: text('user_id').notNull(), requestKey: text('request_key'), providerId: text('provider_id'), modelId: text('model_id'), status: text('status').notNull(), latencyMs: integer('latency_ms'), inputTokens: integer('input_tokens').default(0), outputTokens: integer('output_tokens').default(0), costMicros: bigint('cost_micros', { mode: 'number' }).default(0), errorCode: text('error_code'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() }, (table) => ({ requestUnique: unique().on(table.userId, table.requestKey) }))
export const usageBudgets = pgTable('usage_budgets', { id: text('id').primaryKey(), userId: text('user_id').notNull(), name: text('name').notNull(), period: text('period').notNull(), limitMicros: bigint('limit_micros', { mode: 'number' }).notNull(), usedMicros: bigint('used_micros', { mode: 'number' }).notNull().default(0), enabled: boolean('enabled').notNull().default(true), resetsAt: timestamp('resets_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() }, (table) => ({ budgetUnique: unique().on(table.userId, table.name) }))
export const auditEvents = pgTable('audit_events', { id: text('id').primaryKey(), userId: text('user_id').notNull(), action: text('action').notNull(), resourceType: text('resource_type').notNull(), resourceId: text('resource_id'), requestId: text('request_id'), metadata: jsonb('metadata').notNull().default({}), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() })
export const userRoles = pgTable('user_roles', { id: text('id').primaryKey(), userId: text('user_id').notNull(), role: text('role').notNull().default('member'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() }, (table) => ({ userUnique: unique().on(table.userId) }))
